image: python:3.10-slim

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"


default:
  cache:
    paths:
      - .cache/pip
      - venv/
  before_script:
    - python --version
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate


stages:
  - test
  - deploy


unit_test:
  stage: test
  script:
    - pip3 install -r tests/test_requirements.txt
    - coverage run -m pytest
    - coverage report
    - coverage xml
  coverage: '/TOTAL.*\s([.\d]+)%/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

code_quality:
  stage: test
  script:
    - echo '-- Executing Flake8 --'
    - flake8 src/

#run:
#  script:
#    - python setup.py bdist_wheel
#    # an alternative approach is to install and run:
#  artifacts:
#    paths:
#      - dist/*.whl

# Deploy documentation
pages:
  stage: deploy
  script:
    - pip install sphinx sphinx-rtd-theme
    - cd docs
    - sphinx-apidoc -o . ../src
    - make html
    - mv _build/html/ ../public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

# Deploy to Heroku
production:
  stage: deploy
  script:
    - apt-get update -yq
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP --api_key=$HEROKU_API_KEY
  only:
    - main